# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: IVMA
subtitle: '爱吗/爱码'
description: ''
keywords: 爱吗 爱唯码 爱码
author: 海歌轻唱
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://ivma.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source #资源文件夹，这个文件夹用来存放内容。
public_dir: public #公共文件夹，这个文件夹用于存放生成的站点文件。
tag_dir: tags #标签文件夹
archive_dir: archives #归档文件夹
category_dir: categories #分类文件夹
code_dir: downloads/code #Include code 文件夹，source_dir 下的子目录
i18n_dir: :lang #国际化（i18n）文件夹
skip_render: #跳过指定文件的渲染。详看官方

# Writing
new_post_name: :title.md # 新文章的文件名称
default_layout: post #预设布局
titlecase: false # 把标题转换为 title case
external_link: #在新标签中打开链接
  enable: true # Open external links in new tab
  field: site # 对整个网站（site）生效或仅对文章（post）生效
  exclude: ''
filename_case: 0
render_drafts: false #显示草稿
post_asset_folder: false
relative_link: false
future: true

search: #搜索插件 npm install hexo-generator-search --save
  path: search.xml
  field: post

permalink_pinyin: #正文文件名转拼音插件 npm i hexo-permalink-pinyin --save
  enable: true
  separator: '-' # default: '-'

highlight: #代码块的设置, see Highlight.js section for usage guide
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

prism_plugin:
  mode: 'preprocess' # realtime/preprocess
  theme: 'default'
  line_number: false # default false

prismjs: #代码块的设置, see PrismJS section for usage guide
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-matery
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repo: https://github.com/CIHOO2020/github.io
  branch: gh-pages
